#ifndef QSIMULATIONSTATUSEVENT_H
#define QSIMULATIONSTATUSEVENT_H

//! ----------------------------------------------------------
//! event description:
//! this event is generated by the ccxconsoletofile.cpp class
//! myStatus = 0 (no convergence) 1 (convergence)
//! ----------------------------------------------------------

//! ---
//! Qt
//! ---
#include <QEvent>

class QSimulationStatusEvent: public QEvent
{

public:

    //! ------------
    //! constructor
    //! ------------
    QSimulationStatusEvent(int step, int substep, double time, int status, QString message):
        QEvent(static_cast<QEvent::Type>(2001))
    {
        myStep = step;
        mySubstep = substep;
        myTime = time;
        myStatus = status;
        myMessage = message;
    }

    //! -----------
    //! destructor
    //! -----------
    virtual ~QSimulationStatusEvent() { ; }

    QEvent::Type QSimulationStatusEvent::customEventType = static_cast<QEvent::Type>(QEvent::registerEventType());

    static QEvent::Type type()
    {
        return static_cast<QEvent::Type>(2001);
    }

public:

    int step() { return myStep; }
    int substep() { return mySubstep; }
    double time() { return myTime; }
    int status() {return myStatus; }
    QString getMessage() {return myMessage;}

private:

    int myStep;
    int mySubstep;
    int myStatus;
    double myTime;
    QString myMessage;
};

#endif // QSIMULATIONSTATUSEVENT_H
