#ifndef TABULARDATACOLUMNS_H
#define TABULARDATACOLUMNS_H

//#define NUMBER_OF_COLUMNS_BEFORE_BC_DATA 14     // -1
//#define NUMBER_OF_COLUMNS_BEFORE_BC_DATA 15     // -1
#define NUMBER_OF_COLUMNS_BEFORE_BC_DATA 16     // -1

#define TABULAR_DATA_STEP_NUMBER_COLUMN                     0
#define TABULAR_DATA_STEP_END_TIME_COLUMN                   1
#define TABULAR_DATA_SOLVER_TYPE_COLUMN                     2
#define TABULAR_DATA_TIME_STEP_POLICY                       3
#define TABULAR_DATA_FIELD_PARAMETERS_COLUMN                4
#define TABULAR_DATA_FLUX_CONVERGENCE_COLUMN                5
#define TABULAR_DATA_SOLUTION_CONVERGENCE                   6
#define TABULAR_DATA_TIME_INCREMENTATION_PARAMETERS_COLUMN  7
#define TABULAR_DATA_TIME_INCREMENTATION_TYPE_COLUMN        8
#define TABULAR_DATA_CUTBACK_TYPE_COLUMN                    9
#define TABULAR_DATA_CUTBACK_PARAMETERS_COLUMN              10
#define TABULAR_DATA_LINE_SEARCH_TYPE_COLUMN                11
#define TABULAR_DATA_LINE_SEARCH_PARAMETERS_COLUMN          12
#define TABULAR_DATA_OUPUT_CONTROLS_COLUMN                  13
#define TABULAR_DATA_STORE_RESULTS_AT_COLUMN                14
#define TABULAR_DATA_ANALYSIS_TYPE_COLUMN                   15
#define TABULAR_DATA_TIME_INTEGRATION_COLUMN                16

#endif // TABULARDATACOLUMNS_H
