#ifndef AIS_CUSTOMSIGNATURES_H
#define AIS_CUSTOMSIGNATURES_H

#define CUSTOM_SIGNATURE_THE_FIRST 8

#define CUSTOM_SIGNATURE_COR_MARKER 8
#define CUSTOM_SIGNATURE_MESH_SEGMENT_MARKER 9
#define CUSTOM_SIGNATURE_SPHERE_MARKER 10
#define CUSTOM_SIGNATURE_ARROW_MARKER 11
#define CUSTOM_SIGNATURE_DOUBLE_ARROW_MARKER 12
#define CUSTOM_SIGNATURE_CUSTOM_TRIHEDRON_MARKER 13
#define CUSTOM_SIGNATURE_CURVED_ARROW   14
#define CUSTOM_SIGNATURE_SLICED_MESH    15

#define CUSTOM_SIGNATURE_THE_LAST 15

#endif // AIS_CUSTOMSIGNATURES_H
